The initial version of the Cheesecake Lab's CRA template
CheesecakeLabs/cra-template-ckl-frontend pull request #1
Opened 2020-05-04 22:56 UTC by IbsenFahir

## CKL frontend template

- Initial configuration for CKL Frontend apps

This PR contains the following configs:
  - Sass
  - Jest
  - Eslint
  - Prettier
  - StyleLint
  - Storybook
  - Etc...

Template created based on Create React App documentation: https://create-react-app.dev/docs/custom-templates

2020-05-05 00:18 UTC, DiegoBousfield commented on README.md
> +yarn create react-app <project-name> --template ckl-frontend
I think there's a typo here, the `-` is missing

2020-05-05 12:10 UTC, caiangums commented on README.md
> +- Node v10+
I think it's better to use v12 or v14 (the LTS ones). My option would be v12 😄

2020-05-05 12:13 UTC, caiangums commented on template/.eslintignore
> +.storybook
As we are using `jest`, maybe add here a line with `coverage/` and more test related auto-generated files 😄

2020-05-05 12:15 UTC, caiangums commented on template/README.md
> +
Maybe add here something more related to the fact that we need to fill this with some description about the project, not just the name.

```
> Describe here in a few words what the project is, what problem solves, who is the client. Just a brief description is enough
```

2020-05-05 12:15 UTC, IbsenFahir commented on README.md
> +yarn create react-app <project-name> --template ckl-frontend
With yarn is just like that hehe
https://create-react-app.dev/docs/getting-started

2020-05-05 12:16 UTC, IbsenFahir commented on template/README.md
> +
Nice

2020-05-05 12:16 UTC, vstrapasson commented on template/.huskyrc
> +    "pre-push": "yarn test-ci && yarn eslint && yarn stylelint"
I think we shouldn't run eslint in `pre-push`, because it's redundant, the files that will be pushed have runned previously in `pre-commit` hook. In this current way it will just add more time to run `push`command.

2020-05-05 12:16 UTC, IbsenFahir commented on template/.eslintignore
> +.storybook
Very well observed.

2020-05-05 12:17 UTC, caiangums commented on template/src/components/atoms/example-component/index.js
> +      Ckl boilerplate is up and running!
Maybe change here to `CKL Create React App Template is ready!` to be more related to CRA and a template 😃

2020-05-05 12:43 UTC, natamvo commented
what you guys think to using `.gitkeep` files we setup a structure folder? `ducks, pages, components, store, helpers, services, ....` this way we can list standards for the common things we use for all projects

2020-05-05 13:05 UTC, DiegoBousfield commented on README.md
> +yarn create react-app <project-name> --template ckl-frontend
I didn't know about it, my bad 👍

2020-05-05 14:23 UTC, helderberto commented on README.md
> +- [📕 Storybook 5](https://storybook.js.org/docs/basics/introduction/)
Perhaps, the version of Storybook is irrelevant here.

2020-05-05 14:26 UTC, helderberto commented on package.json
> +  "description": "Cheesecake Labs CRA Template",
Maybe move `description` to above of `keywords` it's more relevant than `keywords` values when starting a new project. What do you think?

2020-05-05 14:27 UTC, helderberto commented on package.json
> +  "license": "MIT",
Considering projects of CKL normally isn't use an `MIT` license I don't know if it makes sense to use.

2020-05-05 14:29 UTC, helderberto commented on template/.codeclimate.yml
> +      config: .eslintrc.json
Personally, I like to use `.eslintrc.js` it's easier when needing to instance things because it's just `.js` file.

2020-05-05 14:29 UTC, helderberto commented on template/.editorconfig
> +
Just remember to remove this empty line.

2020-05-05 14:58 UTC, IbsenFahir commented on template/.huskyrc
> +    "pre-push": "yarn test-ci && yarn eslint && yarn stylelint"
@vstrapasson What about on pre-push we let at least the tests to be run??

2020-05-05 15:01 UTC, IbsenFahir commented on README.md
> +- Node v10+
To be honest that shouldn't be there :/ CRA takes care of it by itself.

2020-05-05 15:06 UTC, helderberto commented on template/.eslintrc.json
> +    "es6": true
Just remember to enable `jest` as global variables to avoid linter errors.

2020-05-05 15:07 UTC, IbsenFahir commented on package.json
> +  "license": "MIT",
I was thinking let this public when everything validated by the team. What do you think?

2020-05-05 15:07 UTC, helderberto commented on template/.eslintrc.json
> +    ]
Maybe break this config to the file `.prettierrc` can be more easily to update when needed.

2020-05-05 15:10 UTC, helderberto commented on template/gitignore
> +.env.production.local
You can just add `.env.*` and `.env`.

2020-05-05 15:11 UTC, helderberto commented on template/public/index.html
> +      content="Cheesecake Labs Boilerplate"
The `description` and `title` can be maintained in `.env`. What do you think?

2020-05-05 15:13 UTC, IbsenFahir commented on template/.eslintrc.json
> +    ]
The general idea of this template is to let these rules more default as possible for two reasons. Be more close to the community and improve the code climate analysis. Then that's why I preferred to let this in just one file since the quantity o rules will be low. But of course, we can discuss more this in the chapter.

2020-05-05 15:15 UTC, helderberto commented on template/src/styles/base.scss
> +  font-size: 16px;
I think you can use the `font-family` from the `variables.scss` and set `font-size` as rem it's better to responsive, if I remember well to calculate more easier the REM sizes you can can something like that:

```css
html {
    font-size: 62.5%;
}

body {
    font-size: 1.6rem; // => Just an example to represent 16px
}
```

2020-05-05 15:16 UTC, helderberto requested changes
Great work! Just some suggestions to enhance the project.

2020-05-05 15:18 UTC, helderberto commented on template/.eslintrc.json
> +    ]
I agree with you about maintaining rules consistent with the community, but it is like I saw for me is more readable and visible when having a separate file with these rules.

2020-05-05 15:19 UTC, helderberto commented on package.json
> +  "license": "MIT",
I think the idea of project is public, but the projects will be created isn't, make sense?

2020-05-05 15:20 UTC, helderberto commented
> what you guys think to using `.gitkeep` files we setup a structure folder? `ducks, pages, components, store, helpers, services, ....` this way we can list standards for the common things we use for all projects

I think it need to be discussed with all team, because some directories isn't used in all projects, but I agree with some cases like: `services` and things is more common with the projects.

2020-05-14 12:42 UTC, caiangums commented on package.json
> +  "license": "MIT",
I think the `MIT` lets the project using it be private. Am I wrong? 🤔

2020-05-14 12:45 UTC, caiangums commented on template/public/index.html
> +      content="Cheesecake Labs Boilerplate"
As a default, it can be done but I think it's better keep this here to be easy to change instead of the need to set Env vars at the server to this be enabled

2020-05-14 12:46 UTC, caiangums commented on template/src/styles/base.scss
> +  font-size: 16px;
`rem` > `em` > `px` 🚀

2020-05-14 12:54 UTC, caiangums commented
My opinion about the `.gitkeep` files to sustain the structure is a bad option. We "force" on using a specific architecture, even when the project is simple or more complex and specific. If we think about what we always use across projects in terms of patterns, I only see **Atomic Design**.

What I think should be created as it is a practice of our daily usage across projects:
* Atomic Components

What I think should not be created:
* Utils
* Helpers
* Services
* Ducks/Store
* Constants

2020-05-14 15:25 UTC, DiegoBousfield commented on template/src/styles/base.scss
> +  font-size: 16px;
I don't think that's a great idea change the `rem` base value from `16px` to `10px`. I've done that before and it led to some confusion when other devs start working on the project, because it's not the default value. And the default value makes easier to use multiples of 8, which is more design friendly.

2020-06-22 12:16 UTC, natamvo commented on template/gitignore
> +.env.production.local
I don't like to keep everything on the root folder, suggestion:
/src/config/.env*
!/src/config/.env.example

2020-06-22 12:16 UTC, natamvo commented on template/.huskyrc
> +  "hooks": {
if we use the gjira on frontend we should not use with husky

2020-06-22 12:26 UTC, IbsenFahir commented on template/gitignore
> +.env.production.local
That was already fixed. You are looking at the old file rsrs

https://github.com/CheesecakeLabs/cra-template-ckl-frontend/blob/ibsen/initial_version/template/gitignore

2020-06-22 12:30 UTC, karranb approved these changes
Awesome! Looking forward to using this 🤘

2020-06-22 12:32 UTC, IbsenFahir commented on template/.huskyrc
> +  "hooks": {
gjira I see as an optional tool (not default at the boilerplate). But I will bring this subject to our chapter to have more opinions.

2020-06-22 12:46 UTC, vstrapasson commented
I think that you forgot the `components/templates/.gitkeep`, or the chapter chose not to keep it in the template? 🤔

2020-06-22 13:32 UTC, helderberto commented on package.json
> +  "license": "MIT",
You're right @caiangums! :D

2020-06-22 13:33 UTC, helderberto commented on template/.eslintrc
> +{
Just to help in the editor's/ide's you can change `.eslintrc` to `.eslintrc.json` to enable JSON formatter.

2020-06-22 13:40 UTC, helderberto commented on template/.prettierrc
> +}
Personally, I like to use these options i.e:
```json
{
  "tabWidth": 2,
  "singleQuote": true,
  "semi": false,
  "trailingComma": "all",
  "printWidth": 120
}
```

You can read more about some topics in the following links:
- [traillingComma: all](https://prettier.io/docs/en/options.html#trailing-commas);
- [printWidth: 120](https://github.com/prettier/prettier/issues/4298);

2020-06-22 13:41 UTC, helderberto approved these changes
💯

2020-06-22 13:51 UTC, carolinaknoll approved these changes

2020-06-22 16:57 UTC, natamvo commented on template/.huskyrc
> +  "hooks": {
we use as default on backend, why there is ok and here is not?

2020-06-22 16:59 UTC, rkpinheiro approved these changes

2020-06-23 14:38 UTC, carolinaknoll commented on template/src/styles/variables.scss
> +// Media queries
Are these media queries supposed to be like this?

I feel like having queries with both `min-width` and `max-width` might be confusing during development.

2020-06-24 12:58 UTC, IbsenFahir commented on template/.huskyrc
> +  "hooks": {
Cause we haven't discussed in the chapter yet

2020-06-25 16:38 UTC, merged